### ISSUE TITLE
attribute errors

### ISSUE THREAD

**Issue by IhabAdarbeh** [Barkhausen-Institut/hermespy#15] opened 2024-07-09 13:40 UTC
Good day,

I am encountering a problem with running the example you provided (https://github.com/Barkhausen-Institut/hermespy/blob/master/_examples/library/getting_started_link.py). I keep receiving attribute errors. Could you please assist me in resolving this issue? I would be grateful for your help.

![Hermes](https://github.com/Barkhausen-Institut/hermespy/assets/172611653/ebddf2da-bd7b-419a-bf37-1809b7a2fbce)

**Comment by IhabAdarbeh** [comment] 2024-07-09 13:50
![Hermes1](https://github.com/Barkhausen-Institut/hermespy/assets/172611653/34692a9d-fca9-4978-8d7b-309173d7e196)

**Comment by adlerjan** [comment] 2024-07-09 15:40
Hello & thank you for reporting.

Since you closed the issue I'll consider it resolved. For anyone investigating similar issues, please ensure you're working with the newest available version of Hermes.

**Comment by IhabAdarbeh** [comment] 2024-07-09 17:40
No, I accidentally closed it, I still have the problem.

**Comment by adlerjan** [comment] 2024-07-09 21:39
How did you install HermesPy?
The issues are almost certainly stemming from trying to run the examples with a deprecated version of the library.

Please make sure you're on the latest version by running
```
pip install --upgrade hermespy==1.3.0
```
if you pulled from pypi or 
```
git pull origin master
pip install -e .
```
if you cloned the repository.

**Comment by IhabAdarbeh** [comment] 2024-07-10 06:46
I installed it with pip and I also have the latest version,

**Comment by adlerjan** [comment] 2024-07-10 07:12
I'm sorry, I can't reproduce the errors on any of my systems.
Could you please run

```
! pip list
```
in your jupyter notebook and make sure hermespy is listed as version `1.3.0` like this?

![grafik](https://github.com/Barkhausen-Institut/hermespy/assets/91198858/880ca314-9ec6-4de7-996b-2830df2d23c4)

The reason I'm rather convinced you're not having the correct version installed is that line 2423 in `core\monte_carlo.py` is not `grid_dimension = ...` as printed in your notebook's error log.

**Comment by IhabAdarbeh** [comment] 2024-07-10 15:56
hello I deleted Hermes library and reinstalled it and now everything works fine thank you.I have another question how can I import an AWGN channel, because I didn't find this channel

**Comment by adlerjan** [comment] 2024-07-10 16:03
The ideal channel that is assumed by default is an AWGN channel, since all devices consider additive noise at the receiver side.
I'll close this issue since it is resolved.
If there's any further questions I'll gladly assist you via email, feel free to contact me at jan.adler@barkhauseninstitut.org .

**Closed as completed by adlerjan** 2024-07-10 16:03 UTC
