### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by userofwireless** [Barkhausen-Institut/hermespy#16] opened 2024-07-20 17:20 UTC
My build is failing with error in the attached file
[hermespy_build_failure_logs.txt](https://github.com/user-attachments/files/16321786/hermespy_build_failure_logs.txt)
 for both "Install from PyPi" and "Install from source" methods.

**Comment by egor-achkasov** [comment] 2024-07-20 19:14
Seems like a missing include in aff3ct's lib cli. Try adding `#include <cstdint>` after line 3 of `hermespy/submodules/affect/lib/cli/src/Types/Argument_type_limited.hpp`.

**Comment by userofwireless** [comment] 2024-07-21 03:48
[hermespy_build_failure_logs_latest.txt](https://github.com/user-attachments/files/16323010/hermespy_build_failure_logs_latest.txt)
Thank you. After I incorporated your suggestion, I was still getting the build error. Taking some clue from the error messages and your suggestions, I added "#include <cstdint>" to header files in "/submodules/affect/lib/cli/src/Types/File_system/" folder. It seems after this, the build progressed quiet a bit but again failed at a later stage (attachment hermespy_build_failure_latest.txt). 

I am not sure if this is an gcc issue. My system is Ubuntu 24.04 and I had installed cmake and gcc as part of building hermespy. My cmake and gcc versions are as follows.

-------
$ cmake --version
cmake version 3.30.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
--------
$ gcc --version
gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-----------------------------------

I tried to "#include <cstdint>" in "Tools/Perf/Transpose/transpose_selector.h" that is included in "/affect/src/Tools/Perf/Transpose/transpose_selector.cpp". However, I am not able to find this header file. So I posted an issue at https://github.com/aff3ct/aff3ct/issues/197

Thank you for your guidance.

**Comment by egor-achkasov** [comment] 2024-07-21 04:27
I guess the aff3ct developers did not tests building with different gcc implementations which may have different includes in standard headers.

For transpose selector see my comment on your issue in affect or add the include directly to the cpp file.

**Comment by userofwireless** [comment] 2024-07-21 07:31
Thank you so much! I am able to build hermespy successfully now after incorporating your guidance.

**Comment by adlerjan** [comment] 2024-07-22 08:15
Glad to hear you're able to build from source.
I'm wondering what the issue with installing the pre-compiled PyPi packages is, could you post the respective error log as well?
Ideally, there shouldn't be any need to rebuild.

**Comment by userofwireless** [comment] 2024-07-22 23:50
Thank you. I am very excited to use hermespy. The error that I encountered while using the pre-compiled PyPi package is the same error that I have uploaded at the beginning of this post. I am using Ubuntu 24.04 and my gcc version is in one of my earlier comments. The issue could be the related to inclusion of <cstdint> for affect submodule.

**Comment by adlerjan** [comment] 2024-07-24 09:49
Which Python version are you on? I don't have an Ubuntu distribution at hand but my linux machines all directly install the pre-compiled package when on Python 3.11 .

**Comment by userofwireless** [comment] 2024-07-25 06:58
I am using Python 3.12. I think this issue could be very specific to my machine and hence may not be a general problem. I am not an experienced programmer. Therefore, I may be making some mistakes that were resulting in the error. Not it is working after including <cstdint>

**Comment by userofwireless** [comment] 2024-07-25 06:59
Sorry for the typo. I meant "Now it is working after including <cstdint>"

**Comment by userofwireless** [comment] 2024-07-25 06:59
including cstdint

**Comment by adlerjan** [comment] 2024-07-25 07:37
Alright. The culprit is Python 3.12 . The latest release of HermesPy officially only supports Python <=3.11, so you can consider yourself the first official 3.12 tester :) (although I don't expect any issues moving to a higher Minor version).

**Closed as completed by adlerjan** 2024-07-25 07:37 UTC

**Comment by egor-achkasov** [comment] 2024-07-25 12:05
A side note for anyone reading this in the future. The issue is caused by changes in gcc 13. See the first item in https://gcc.gnu.org/gcc-13/porting_to.html
